app:
  name: ${APP_NAME:default}
  version: ${APP_VERSION:1.0.0}
  token:
    secret: flexi_code
    expire: 7200

storage:
  driver: mysql
  auto-migrate: true
  connection: root:123456@tcp(192.168.56.100:3306)/flexi_code?charset=utf8mb4&parseTime=True&loc=Local